.TH "Background" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Background \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Background\&.hpp>\fP
.PP
Dziedziczy \fBStandardReferences\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBBackground\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP (const float &dt, const float &player_y)"
.br
.ti -1c
.RI "void \fBinit\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SS "Dodatkowe Dziedziczone Składowe"
.SH "Opis szczegółowy"
.PP 
Klasa przewijalnego tla w grze 
.PP
Definicja w linii 8 pliku Background\&.hpp\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "Background::Background ()"

.PP
Definicja w linii 4 pliku Background\&.cpp\&.
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void Background::draw ()"

.PP
Definicja w linii 27 pliku Background\&.cpp\&.
.SS "void Background::init ()"

.PP
Definicja w linii 39 pliku Background\&.cpp\&.
.SS "void Background::reset ()"

.PP
Definicja w linii 52 pliku Background\&.cpp\&.
.SS "void Background::update (const float &dt, const float &player_y)"

.PP
Definicja w linii 12 pliku Background\&.cpp\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
