.TH "include/Const.hpp" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Const.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Definicje"

.in +1c
.ti -1c
.RI "#define \fBRENDER_GL\fP"
.br
.ti -1c
.RI "#define \fBLIGHT_GL\fP"
.br
.ti -1c
.RI "#define \fBTEXTURE\fP"
.br
.ti -1c
.RI "#define \fBVERSION\fP   ' build 0\&.3 '"
.br
.in -1c
.SS "Funkcje"

.in +1c
.ti -1c
.RI "const unsigned short \fBWIDHT\fP (1400)"
.br
.ti -1c
.RI "const unsigned short \fBHEIGHT\fP (900)"
.br
.ti -1c
.RI "const float \fBSPLASH_TIME\fP (1\&.7)"
.br
.ti -1c
.RI "const unsigned int \fBLEVEL_WIDHT\fP (30000)"
.br
.ti -1c
.RI "const unsigned int \fBLEVEL_HEIGHT\fP (25)"
.br
.ti -1c
.RI "const ushort \fBMAX_SCREEN_HEIGHT\fP (1080)"
.br
.ti -1c
.RI "const ushort \fBMAX_SCREEN_WIDTH\fP (1920)"
.br
.ti -1c
.RI "const ushort \fBMIN_SCREEN_WIDTH\fP (800)"
.br
.ti -1c
.RI "const ushort \fBMIN_SCREEN_HEIGHT\fP (600)"
.br
.ti -1c
.RI "const ushort \fBCOLISION_WITH_ENEMY\fP (10000)"
.br
.ti -1c
.RI "const SDL_Color \fBBLACK_FONT_COLOR\fP ({8, 16, 29})"
.br
.ti -1c
.RI "const SDL_Color \fBWHITE_FONT_COLOR\fP ({240, 240, 250})"
.br
.ti -1c
.RI "const SDL_Color \fBYELLOW_FONT_COLOR\fP ({235, 190, 0})"
.br
.in -1c
.SH "Dokumentacja definicji"
.PP 
.SS "#define LIGHT_GL"

.PP
Definicja w linii 9 pliku Const\&.hpp\&.
.SS "#define RENDER_GL"

.PP
Definicja w linii 8 pliku Const\&.hpp\&.
.SS "#define TEXTURE"

.PP
Definicja w linii 13 pliku Const\&.hpp\&.
.SS "#define VERSION   ' build 0\&.3 '"

.PP
Definicja w linii 15 pliku Const\&.hpp\&.
.SH "Dokumentacja funkcji"
.PP 
.SS "const SDL_Color BLACK_FONT_COLOR ()"

.SS "const ushort COLISION_WITH_ENEMY (10000)"

.SS "const unsigned short HEIGHT (900)"

.SS "const unsigned int LEVEL_HEIGHT (25)"

.SS "const unsigned int LEVEL_WIDHT (30000)"

.SS "const ushort MAX_SCREEN_HEIGHT (1080)"

.SS "const ushort MAX_SCREEN_WIDTH (1920)"

.SS "const ushort MIN_SCREEN_HEIGHT (600)"

.SS "const ushort MIN_SCREEN_WIDTH (800)"

.SS "const float SPLASH_TIME (1\&.7)"

.SS "const SDL_Color WHITE_FONT_COLOR ()"

.SS "const unsigned short WIDHT (1400)"

.SS "const SDL_Color YELLOW_FONT_COLOR ()"

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
