.TH "Enemy" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enemy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Enemy\&.hpp>\fP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBEnemy\fP (ushort R, ushort C, ushort ID)"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP (const float &dt)"
.br
.ti -1c
.RI "bool \fBisColidate\fP (\fBRect\fP rct)"
.br
.ti -1c
.RI "float \fBgetPosX\fP () const "
.br
.ti -1c
.RI "void \fBsetPosX\fP (float posX)"
.br
.ti -1c
.RI "float \fBgetPosY\fP () const "
.br
.ti -1c
.RI "void \fBsetPosY\fP (float posY)"
.br
.ti -1c
.RI "ushort \fBgetColumn\fP () const "
.br
.ti -1c
.RI "ushort \fBgetId\fP () const "
.br
.ti -1c
.RI "ushort \fBgetRow\fP () const "
.br
.ti -1c
.RI "float \fBgetOffset\fP () const "
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Definicja w linii 7 pliku Enemy\&.hpp\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "Enemy::Enemy (ushortR, ushortC, ushortID)"

.PP
Definicja w linii 4 pliku Enemy\&.cpp\&.
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void Enemy::draw ()"

.PP
Definicja w linii 13 pliku Enemy\&.cpp\&.
.SS "ushort Enemy::getColumn () const\fC [inline]\fP"

.PP
Definicja w linii 33 pliku Enemy\&.hpp\&.
.SS "ushort Enemy::getId () const\fC [inline]\fP"

.PP
Definicja w linii 37 pliku Enemy\&.hpp\&.
.SS "float Enemy::getOffset () const\fC [inline]\fP"

.PP
Definicja w linii 45 pliku Enemy\&.hpp\&.
.SS "float Enemy::getPosX () const\fC [inline]\fP"

.PP
Definicja w linii 17 pliku Enemy\&.hpp\&.
.SS "float Enemy::getPosY () const\fC [inline]\fP"

.PP
Definicja w linii 25 pliku Enemy\&.hpp\&.
.SS "ushort Enemy::getRow () const\fC [inline]\fP"

.PP
Definicja w linii 41 pliku Enemy\&.hpp\&.
.SS "bool Enemy::isColidate (\fBRect\fPrct)\fC [inline]\fP"

.PP
Definicja w linii 15 pliku Enemy\&.hpp\&.
.SS "void Enemy::setPosX (floatposX)\fC [inline]\fP"

.PP
Definicja w linii 21 pliku Enemy\&.hpp\&.
.SS "void Enemy::setPosY (floatposY)\fC [inline]\fP"

.PP
Definicja w linii 29 pliku Enemy\&.hpp\&.
.SS "void Enemy::update (const float &dt)"

.PP
Definicja w linii 27 pliku Enemy\&.cpp\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
