.TH "Gamespace::HighscoreItem" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gamespace::HighscoreItem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Headers\&.hpp>\fP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBHighscoreItem\fP (string n, string p='')"
.br
.ti -1c
.RI "\fBHighscoreItem\fP ()"
.br
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "uint \fBpoints\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Definicja w linii 96 pliku Headers\&.hpp\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "Gamespace::HighscoreItem::HighscoreItem (stringn, stringp = \fC''\fP)\fC [inline]\fP"

.PP
Definicja w linii 100 pliku Headers\&.hpp\&.
.SS "Gamespace::HighscoreItem::HighscoreItem ()\fC [inline]\fP"

.PP
Definicja w linii 103 pliku Headers\&.hpp\&.
.SH "Dokumentacja atrybutów składowych"
.PP 
.SS "string Gamespace::HighscoreItem::name"

.PP
Definicja w linii 97 pliku Headers\&.hpp\&.
.SS "uint Gamespace::HighscoreItem::points"

.PP
Definicja w linii 98 pliku Headers\&.hpp\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
