.TH "Gamespace::ColisionSide" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Gamespace::ColisionSide \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Headers\&.hpp>\fP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBColisionSide\fP ()"
.br
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "bool \fBup\fP"
.br
.ti -1c
.RI "bool \fBdown\fP"
.br
.ti -1c
.RI "bool \fBright\fP"
.br
.ti -1c
.RI "bool \fBleft\fP"
.br
.ti -1c
.RI "float \fBpos_Y_px\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Definicja w linii 82 pliku Headers\&.hpp\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "Gamespace::ColisionSide::ColisionSide ()\fC [inline]\fP"

.PP
Definicja w linii 90 pliku Headers\&.hpp\&.
.SH "Dokumentacja atrybutów składowych"
.PP 
.SS "bool Gamespace::ColisionSide::down"

.PP
Definicja w linii 84 pliku Headers\&.hpp\&.
.SS "bool Gamespace::ColisionSide::left"

.PP
Definicja w linii 86 pliku Headers\&.hpp\&.
.SS "float Gamespace::ColisionSide::pos_Y_px"

.PP
Definicja w linii 88 pliku Headers\&.hpp\&.
.SS "bool Gamespace::ColisionSide::right"

.PP
Definicja w linii 85 pliku Headers\&.hpp\&.
.SS "bool Gamespace::ColisionSide::up"

.PP
Definicja w linii 83 pliku Headers\&.hpp\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
