.TH "Highscore" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Highscore \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Highscore\&.hpp>\fP
.PP
Dziedziczy \fBStandardReferences\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBHighscore\fP ()"
.br
.ti -1c
.RI "void \fBshow\fP ()"
.br
.ti -1c
.RI "void \fBcolision\fP (short type)"
.br
.ti -1c
.RI "void \fBload\fP ()"
.br
.ti -1c
.RI "void \fBsave\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP ()"
.br
.ti -1c
.RI "void \fBpressedBackspace\fP ()"
.br
.ti -1c
.RI "void \fBpressedChar\fP (char Char)"
.br
.ti -1c
.RI "void \fBupdate\fP (const float &dt)"
.br
.in -1c
.SS "Dodatkowe Dziedziczone Składowe"
.SH "Opis szczegółowy"
.PP 
Definicja w linii 8 pliku Highscore\&.hpp\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "Highscore::Highscore ()"

.PP
Definicja w linii 8 pliku Highscore\&.cpp\&.
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void Highscore::colision (shorttype)"

.PP
Definicja w linii 139 pliku Highscore\&.cpp\&.
.SS "void Highscore::draw ()"
mozliwosc wpisania imienia gracza 
.PP
Definicja w linii 42 pliku Highscore\&.cpp\&.
.SS "void Highscore::load ()"
Wczxytywanie zapisanych wynikow z pliku 
.PP
Definicja w linii 145 pliku Highscore\&.cpp\&.
.SS "void Highscore::pressedBackspace ()"
usuwanie znakow z imienia gracza 
.PP
Definicja w linii 30 pliku Highscore\&.cpp\&.
.SS "void Highscore::pressedChar (charChar)"
Wpisywanie imienia gracza 
.PP
Definicja w linii 36 pliku Highscore\&.cpp\&.
.SS "void Highscore::save ()"

.PP
Definicja w linii 194 pliku Highscore\&.cpp\&.
.SS "void Highscore::show ()"
\fBHighscore\fP widziane z menu 
.PP
Definicja w linii 93 pliku Highscore\&.cpp\&.
.SS "void Highscore::update (const float &dt)"

.PP
Definicja w linii 235 pliku Highscore\&.cpp\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
