.TH "src/main.cpp" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Headers\&.hpp'\fP
.br
\fC#include 'App\&.hpp'\fP
.br
\fC#include 'Property\&.hpp'\fP
.br
\fC#include 'Resource\&.hpp'\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Dokumentacja funkcji"
.PP 
.SS "int main (intargc, char *argv[])"
AstroRush 2D game 
.PP
Definicja w linii 7 pliku main\&.cpp\&.
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
