.TH "src/MapManager.cpp" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/MapManager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'MapManager\&.hpp'\fP
.br
\fC#include 'Sprite\&.hpp'\fP
.br
\fC#include 'SpriteManager\&.hpp'\fP
.br
\fC#include 'App\&.hpp'\fP
.br

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
