.TH "src/Menu.cpp" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Menu.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/Menu\&.hpp'\fP
.br
\fC#include 'App\&.hpp'\fP
.br
\fC#include 'Game\&.hpp'\fP
.br

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
