.TH "include/Play.hpp" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Play.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Player\&.hpp'\fP
.br
\fC#include 'MapManager\&.hpp'\fP
.br
\fC#include 'Highscore\&.hpp'\fP
.br
\fC#include 'LiveBar\&.hpp'\fP
.br
\fC#include 'SpriteManager\&.hpp'\fP
.br
\fC#include 'EnemyManager\&.hpp'\fP
.br
\fC#include 'StandardReferences\&.hpp'\fP
.br
\fC#include 'Background\&.hpp'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBPlay\fP"
.br
.in -1c
.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
