.TH "src/Splash.cpp" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Splash.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include/Splash\&.hpp'\fP
.br
\fC#include '\&.\&./include/MapManager\&.hpp'\fP
.br
\fC#include 'Headers\&.hpp'\fP
.br

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
