.TH "SpriteConfig" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteConfig \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Spriteconfig\&.hpp>\fP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBSpriteConfig\fP (short X, short Y, short W, short H, short AX, short AY, float FT, short FC, ushort L, bool R=true)"
.br
.in -1c
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "short \fBpos_x\fP"
.br
.ti -1c
.RI "short \fBpos_y\fP"
.br
.ti -1c
.RI "short \fBwidth\fP"
.br
.ti -1c
.RI "short \fBheight\fP"
.br
.ti -1c
.RI "short \fBatlas_x\fP"
.br
.ti -1c
.RI "short \fBatlas_y\fP"
.br
.ti -1c
.RI "float \fBframe_duration_time\fP"
.br
.ti -1c
.RI "short \fBframe_count\fP"
.br
.ti -1c
.RI "ushort \fBlevel\fP"
.br
.ti -1c
.RI "bool \fBloop\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Struktura przechowujaca wszystkie informacje o \fBSprite\fP 
.PP
Definicja w linii 6 pliku Spriteconfig\&.hpp\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "SpriteConfig::SpriteConfig (shortX, shortY, shortW, shortH, shortAX, shortAY, floatFT, shortFC, ushortL, boolR = \fCtrue\fP)\fC [inline]\fP"

.PP
Definicja w linii 10 pliku Spriteconfig\&.hpp\&.
.SH "Dokumentacja atrybutów składowych"
.PP 
.SS "short SpriteConfig::atlas_x"

.PP
Definicja w linii 20 pliku Spriteconfig\&.hpp\&.
.SS "short SpriteConfig::atlas_y"

.PP
Definicja w linii 21 pliku Spriteconfig\&.hpp\&.
.SS "short SpriteConfig::frame_count"

.PP
Definicja w linii 24 pliku Spriteconfig\&.hpp\&.
.SS "float SpriteConfig::frame_duration_time"

.PP
Definicja w linii 23 pliku Spriteconfig\&.hpp\&.
.SS "short SpriteConfig::height"

.PP
Definicja w linii 18 pliku Spriteconfig\&.hpp\&.
.SS "ushort SpriteConfig::level"

.PP
Definicja w linii 26 pliku Spriteconfig\&.hpp\&.
.SS "bool SpriteConfig::loop"

.PP
Definicja w linii 27 pliku Spriteconfig\&.hpp\&.
.SS "short SpriteConfig::pos_x"

.PP
Definicja w linii 14 pliku Spriteconfig\&.hpp\&.
.SS "short SpriteConfig::pos_y"

.PP
Definicja w linii 15 pliku Spriteconfig\&.hpp\&.
.SS "short SpriteConfig::width"

.PP
Definicja w linii 17 pliku Spriteconfig\&.hpp\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
