.TH "StandardReferences" 3 "Pn, 11 mar 2013" "Version 0.0.3" "AstroRush" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StandardReferences \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StandardReferences\&.hpp>\fP
.PP
Dziedziczona przez \fBBackground\fP, \fBGame\fP\fC [private]\fP, \fBHighscore\fP\fC [private]\fP, \fBLiveBar\fP, \fBMap\fP\fC [private]\fP, \fBMapManager\fP\fC [private]\fP, \fBMenu\fP\fC [private]\fP, \fBMenuItem\fP\fC [private]\fP, \fBPlay\fP\fC [private]\fP, \fBPlayer\fP\fC [private]\fP i \fBSprite\fP\fC [private]\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBStandardReferences\fP ()"
.br
.in -1c
.SS "Atrybuty chronione"

.in +1c
.ti -1c
.RI "\fBRenderer\fP * \fBpRendererPtr\fP"
.br
.ti -1c
.RI "\fBWriter\fP * \fBpWriterPtr\fP"
.br
.ti -1c
.RI "\fBSoundManager\fP * \fBpSoundManagerPtr\fP"
.br
.ti -1c
.RI "short \fBpScreenWidth\fP"
.br
.ti -1c
.RI "short \fBpScreenHeight\fP"
.br
.ti -1c
.RI "\fBLogger\fP \fBlogger\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Definicja w linii 11 pliku StandardReferences\&.hpp\&.
.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "StandardReferences::StandardReferences ()\fC [inline]\fP"

.PP
Definicja w linii 13 pliku StandardReferences\&.hpp\&.
.SH "Dokumentacja atrybutów składowych"
.PP 
.SS "\fBLogger\fP StandardReferences::logger\fC [protected]\fP"

.PP
Definicja w linii 30 pliku StandardReferences\&.hpp\&.
.SS "\fBRenderer\fP* StandardReferences::pRendererPtr\fC [protected]\fP"

.PP
Definicja w linii 24 pliku StandardReferences\&.hpp\&.
.SS "short StandardReferences::pScreenHeight\fC [protected]\fP"

.PP
Definicja w linii 29 pliku StandardReferences\&.hpp\&.
.SS "short StandardReferences::pScreenWidth\fC [protected]\fP"

.PP
Definicja w linii 28 pliku StandardReferences\&.hpp\&.
.SS "\fBSoundManager\fP* StandardReferences::pSoundManagerPtr\fC [protected]\fP"

.PP
Definicja w linii 26 pliku StandardReferences\&.hpp\&.
.SS "\fBWriter\fP* StandardReferences::pWriterPtr\fC [protected]\fP"

.PP
Definicja w linii 25 pliku StandardReferences\&.hpp\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla AstroRush\&.
